FROM aarch64/ubuntu

#AUTHOR bmwshop@gmail.com
MAINTAINER nuculur@gmail.com

# This is the base container for the Jetson TX2 board with drivers (without cuda)
RUN apt-get update && apt-get install -y apt-utils bzip2 curl sudo unp && apt-get clean && rm -rf /var/cache/apt
WORKDIR /tmp

# drivers first
RUN curl -sL http://developer.nvidia.com/embedded/dlc/l4t-jetson-tx2-driver-package-28-1 | tar xvfj -
RUN chown root /etc/passwd /etc/sudoers /usr/lib/sudo/sudoers.so /etc/sudoers.d/README
RUN /tmp/Linux_for_Tegra/apply_binaries.sh -r / && rm -fr /tmp/*

## Pull the rest of the jetpack and install
RUN curl http://developer.download.nvidia.com/devzone/devcenter/mobile/jetpack_l4t/013/linux-x64/cuda-repo-l4t-8-0-local_8.0.84-1_arm64.deb -so cuda-repo-l4t_arm64.deb && dpkg -i /tmp/cuda-repo-l4t_arm64.deb

RUN apt-get update && apt-get install -y cuda-toolkit-8.0 && rm -fr /tmp/* && apt-get clean && rm -rf /var/cache/apt

RUN curl http://developer.download.nvidia.com/devzone/devcenter/mobile/jetpack_l4t/013/linux-x64/libcudnn6_6.0.21-1+cuda8.0_arm64.deb -so /tmp/libcudnn_arm64.deb && dpkg -i /tmp/libcudnn_arm64.deb && rm -fr /tmp/*

RUN curl http://developer.download.nvidia.com/devzone/devcenter/mobile/jetpack_l4t/013/linux-x64/libcudnn6-dev_6.0.21-1+cuda8.0_arm64.deb -so /tmp/libcudnn-dev_arm64.deb && dpkg -i /tmp/libcudnn-dev_arm64.deb && rm -fr /tmp/*

## Install libs: L4T, CUDA, cuDNN
#RUN dpkg -i /tmp/cuda-repo-l4t_arm64.deb
#RUN apt-get update && apt-get install -y cuda-toolkit-8.0
#RUN dpkg -i /tmp/libcudnn_arm64.deb /tmp/libcudnn-dev_arm64.deb
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/aarch64-linux-gnu/tegra

# D.R. -- need to do this for some strange reason (for jetson tx2)
RUN ln -s /usr/lib/aarch64-linux-gnu/libcuda.so /usr/lib/aarch64-linux-gnu/libcuda.so.1

## Clean up
RUN apt-get -y autoremove && apt-get -y autoclean
RUN rm -rf /var/cuda-repo-8-0-local/*.deb
RUN rm -rf /usr/local/cuda-8.0/doc/*
RUN rm -rf /root/src/opencv*
RUN rm -rf /root/src/jetsonhacks
#RUN mv /usr/local/cuda-8.0/samples/2_Graphics/ /usr/local/cuda-8.0/
#RUN rm -rf /usr/local/cuda-8.0/samples/*
#RUN mv /usr/local/cuda-8.0/2_Graphics/ /usr/local/cuda-8.0/samples/

#Download additional docs,libs#-----------------------------------------------------------------------
#Optional: Docs#RUN curl http://developer.download.nvidia.com/devzone/devcenter/mobile/jetpack_l4t/013/common/jetpack_docs.zip -so /tmp/jetpack_docs.zip
#RUN curl http://developer.download.nvidia.com/devzone/devcenter/mobile/jetpack_l4t/013/linux-x64/NVIDIA_VisionWorks_1.6_Docs.zip -so /tmp/NVIDIA_VisionWorks_1.6_Docs.zip
#RUN curl http://developer.download.nvidia.com/devzone/devcenter/mobile/jetpack_l4t/013/linux-x64/Tegra_Multimedia_API_R28.1.0_aarch64.tbz2 -so /tmp/Tegra_Multimedia_API_R28.1.0_aarch64.tbz2
#RUN curl http://developer.download.nvidia.com/devzone/devcenter/mobile/jetpack_l4t/013/linux-x64/host-x64-linux-public-3.8.450-a527a18.tar.gz -so host-x64-linux-public-3.8.450-a527a18.tar.gz
#RUN curl http://developer.download.nvidia.com/devzone/devcenter/mobile/jetpack_l4t/013/linux-x64/libcudnn6-doc_6.0.21-1+cuda8.0_arm64.deb -so /tmp/libcudnn6-doc_6.0.21-1+cuda8.0_arm64.deb
#RUN curl http://developer.download.nvidia.com/devzone/devcenter/mobile/jetpack_l4t/006/linux-x64/libopencv4tegra-repo_2.4.13-17-g5317135_amd64_ubuntu-14.04.deb -so /tmp/libopencv4tegra-repo_2.4.13-17-g5317135_amd64_ubuntu-14.04.deb  
#RUN curl http://developer.download.nvidia.com/devzone/devcenter/mobile/jetpack_l4t/013/linux-x64/libopencv4tegra-repo_2.4.13-17-g5317135_arm64_l4t-r24.deb -so /tmp/libopencv4tegra-repo_2.4.13-17-g5317135_arm64_l4t-r24.deb
#RUN curl http://developer.download.nvidia.com/devzone/devcenter/mobile/jetpack_l4t/013/linux-x64/libvisionworks-repo_1.6.0.193n_amd64_ubuntu-14.04.deb -so /tmp/libvisionworks-repo_1.6.0.193n_amd64_ubuntu-14.04.deb
#RUN curl http://developer.download.nvidia.com/devzone/devcenter/mobile/jetpack_l4t/013/linux-x64/libvisionworks-repo_1.6.0.233n_arm64_l4t-r26.deb -so /tmp/libvisionworks-repo_1.6.0.233n_arm64_l4t-r26.deb
#RUN curl http://developer.download.nvidia.com/devzone/devcenter/mobile/jetpack_l4t/013/linux-x64/libvisionworks-sfm-repo_0.90.1_amd64_ubuntu-14.04.deb -so /tmp/libvisionworks-sfm-repo_0.90.1_amd64_ubuntu-14.04.deb
#RUN curl http://developer.download.nvidia.com/devzone/devcenter/mobile/jetpack_l4t/013/linux-x64/libvisionworks-sfm-repo_0.90.1_arm64_l4t-r26.deb -so /tmp/libvisionworks-sfm-repo_0.90.1_arm64_l4t-r26.deb
#RUN curl http://developer.download.nvidia.com/devzone/devcenter/mobile/jetpack_l4t/013/linux-x64/libvisionworks-tracking-repo_0.88.0_amd64_ubuntu-14.04.deb -so libvisionworks-tracking-repo_0.88.0_amd64_ubuntu-14.04.deb
#RUN curl http://developer.download.nvidia.com/devzone/devcenter/mobile/jetpack_l4t/013/linux-x64/libvisionworks-tracking-repo_0.88.0_arm64_l4t-r26.deb -so /tmp/libvisionworks-tracking-repo_0.88.0_arm64_l4t-r26.deb
#RUN curl http:///developer.download.nvidia.com/devzone/devcenter/mobile/jetpack_l4t/013/linux-x64/nv-gie-repo-ubuntu1604-ga-cuda8.0-trt2.1-20170614_1-1_arm64.deb -so /tmp/nv-gie-repo-ubuntu1604-ga-cuda8.0-trt2.1-20170614_1-1_arm64.deb

